---
- name: Install postgresql package
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - "{{postgresql_pkg_name}}"
    - python-psycopg2

- name: Copy pg_hba.conf
  copy:
    src: pg_hba.conf
    dest: "{{postgresql_cfgdir}}/"
    mode: 0600

- name: Create user for the db
  become: yes
  become_user: "{{postgresql_user}}"
  postgresql_user:
    name: "{{postgresql_db_user}}"
    password: "{{postgresql_db_passwd}}"
    state: present

- name: Create database
  become: yes
  become_user: "{{postgresql_user}}"
  postgresql_db:
    name: "{{postgresql_db_name}}"
    owner: "{{postgresql_db_user}}"
    encoding: UTF-8
    template: template1
    state: present

- name: Get stats of monitrc
  stat: 
    path: "{{monit_dir}}/monitrc"
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Template of postgres.monit
  template:
    src: postgres.monit.j2
    dest: "{{monit_includedir}}/postgres.monit"
    mode: 0644
  vars:
    pattern: ''
    pidfile: "{{postgresql_pidfile}}"
  when: st_monitrc.stat.exists
  notify: Restart_monit.service
